export const CHARACTERS = {
  fireDucky: {
    id: 'fireDucky',
    name: 'Fire Ducky',
    color: 0xff4400,
    specialAttack: 'FireballAttack',
    cost: 0,
    description: 'Shoots fireballs horizontally!',
    unlocked: true,
  },
  bubbleDucky: {
    id: 'bubbleDucky',
    name: 'Bubble Ducky',
    color: 0x00ccff,
    specialAttack: 'BubbleAttack',
    cost: 25,
    description: 'Freezes nearby octopuses in bubbles!',
    unlocked: false,
  },
  lightningDucky: {
    id: 'lightningDucky',
    name: 'Lightning Ducky',
    color: 0xffff00,
    specialAttack: 'LightningAttack',
    cost: 50,
    description: 'Strikes all nearby enemies with lightning!',
    unlocked: false,
  },
  bombingDucky: {
    id: 'bombingDucky',
    name: 'Bombing Ducky',
    color: 0x333333,
    specialAttack: 'BombAttack',
    cost: 75,
    description: 'Rains bombs from the sky!',
    unlocked: false,
  },
  luckyDucky: {
    id: 'luckyDucky',
    name: 'Lucky Ducky',
    color: 0x00ff88,
    specialAttack: 'LuckyAttack',
    cost: 100,
    description: 'Randomly uses Bubble, Lightning, or Bomb!',
    unlocked: false,
  },
  surfDucky: {
    id: 'surfDucky',
    name: 'Surf Ducky',
    color: 0x00bcd4,
    specialAttack: 'SurfAttack',
    cost: 125,
    description: 'Rides a tidal wave that wipes out everything!',
    unlocked: false,
  },
  coconutDucky: {
    id: 'coconutDucky',
    name: 'Coconut Ducky',
    color: 0x8d6e63,
    specialAttack: 'CoconutAttack',
    cost: 150,
    description: 'Rains coconuts on ALL enemies in the level!',
    unlocked: false,
  },
  sandDucky: {
    id: 'sandDucky',
    name: 'Sand Ducky',
    color: 0xffd54f,
    specialAttack: 'SandstormAttack',
    cost: 175,
    description: 'Sandstorm freezes every enemy for 5 seconds!',
    unlocked: false,
  },
  sharkDucky: {
    id: 'sharkDucky',
    name: 'Shark Ducky',
    color: 0x546e7a,
    specialAttack: 'SharkAttack',
    cost: 200,
    description: 'Shark zooms through enemies twice!',
    unlocked: false,
  },
  seashellDucky: {
    id: 'seashellDucky',
    name: 'Seashell Ducky',
    color: 0xf48fb1,
    specialAttack: 'SeashellAttack',
    cost: 225,
    description: 'Sonic blast kills nearby, blows away the rest!',
    unlocked: false,
  },
};

export const CHARACTER_ORDER = [
  'fireDucky',
  'bubbleDucky',
  'lightningDucky',
  'bombingDucky',
  'luckyDucky',
  'surfDucky',
  'coconutDucky',
  'sandDucky',
  'sharkDucky',
  'seashellDucky',
];

export const CLASSIC_ORDER = [
  'fireDucky',
  'bubbleDucky',
  'lightningDucky',
  'bombingDucky',
  'luckyDucky',
];

export const BEACH_ORDER = [
  'surfDucky',
  'coconutDucky',
  'sandDucky',
  'sharkDucky',
  'seashellDucky',
];
